spring:
  datasource:
    url: 'jdbc:postgresql://localhost:15433/processors_db'
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/main-changelog.yaml
  kafka:
    listener.ack-mode: manual
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";

storage:
  url: http://localhost:9002
  port: 9002
  accessKey: user
  secretKey: password
  secure: false
  bucket: minio-storage
  image-size: 10485760 #10 Mb
  ttl: 15 #15 minutes

app:
  images:
    wip:
      topic: images.wip
      partitions: 3
      group-id: group.images.wip
      transactional-id: custom-transactional-scharr
    done:
      topic: images.done

filter:
  type: "IMAGGA"

api:
  key: acc_2ce44f273f71452
  secret: a75b7c2e4c16a8c693b6b4c0d95a945a

server:
  port: 8090

resilience4j:
  ratelimiter:
    instances:
      customRateLimiter:
        limitForPeriod: 4
        limitRefreshPeriod: 60s
        timeoutDuration: 10s
  retry:
    instances:
      customRetry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.TooManyRequests
          - org.springframework.web.reactive.function.client.WebClientResponseException.InternalServerError
          - org.springframework.web.reactive.function.client.WebClientResponseException.NotImplemented
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadGateway
          - org.springframework.web.reactive.function.client.WebClientResponseException.ServiceUnavailable
          - org.springframework.web.reactive.function.client.WebClientResponseException.GatewayTimeout
  circuitbreaker:
    instances:
      customCircuitBreaker:
        failure-rate-threshold: 75
        sliding-window-size: 4
        wait-duration-in-open-state: 10s
        sliding-window-type: COUNT_BASED