spring:
  datasource:
    url: 'jdbc:postgresql://localhost:15433/processors_db'
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/main-changelog.yaml
  kafka:
    listener.ack-mode: manual
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";

storage:
  url: http://localhost:9002
  port: 9002
  accessKey: user
  secretKey: password
  secure: false
  bucket: minio-storage
  image-size: 10485760 #10 Mb
  ttl: 1 #1 day

app:
  images:
    wip:
      topic: images.wip
      partitions: 3
      group-id: group.images.wip
      transactional-id: custom-transactional-scharr
    done:
      topic: images.done

filter:
  type: "SCHARR"